// <auto-generated />
using System;
using ComplementaryServices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace complementaryservice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComplementaryServiceDbContext))]
    [Migration("20260114235526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplementaryServices.Domain.Entities.ComplementaryService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ReservationId");

                    b.ToTable("ComplementaryServices", (string)null);
                });

            modelBuilder.Entity("ComplementaryServices.Domain.Entities.ServiceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("ComplementaryServices.Domain.Entities.ComplementaryService", b =>
                {
                    b.OwnsOne("ComplementaryServices.Domain.ValueObjects.ServiceType", "ServiceType", b1 =>
                        {
                            b1.Property<Guid>("ComplementaryServiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ServiceType");

                            b1.HasKey("ComplementaryServiceId");

                            b1.ToTable("ComplementaryServices");

                            b1.WithOwner()
                                .HasForeignKey("ComplementaryServiceId");
                        });

                    b.OwnsOne("ComplementaryServices.Domain.ValueObjects.ProviderResponse", "ProviderResponse", b1 =>
                        {
                            b1.Property<Guid>("ComplementaryServiceId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("EstimatedTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ProviderEstimatedTime");

                            b1.Property<bool>("IsAvailable")
                                .HasColumnType("boolean")
                                .HasColumnName("ProviderIsAvailable");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ProviderMessage");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ProviderPrice");

                            b1.Property<string>("ProviderId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ProviderResponseId");

                            b1.HasKey("ComplementaryServiceId");

                            b1.ToTable("ComplementaryServices");

                            b1.WithOwner()
                                .HasForeignKey("ComplementaryServiceId");
                        });

                    b.OwnsOne("ComplementaryServices.Domain.ValueObjects.ServiceStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("ComplementaryServiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Status");

                            b1.HasKey("ComplementaryServiceId");

                            b1.ToTable("ComplementaryServices");

                            b1.WithOwner()
                                .HasForeignKey("ComplementaryServiceId");
                        });

                    b.Navigation("ProviderResponse")
                        .IsRequired();

                    b.Navigation("ServiceType")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("ComplementaryServices.Domain.Entities.ServiceProvider", b =>
                {
                    b.OwnsOne("ComplementaryServices.Domain.ValueObjects.ServiceType", "ServiceType", b1 =>
                        {
                            b1.Property<Guid>("ServiceProviderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ServiceType");

                            b1.HasKey("ServiceProviderId");

                            b1.ToTable("ServiceProviders");

                            b1.WithOwner()
                                .HasForeignKey("ServiceProviderId");
                        });

                    b.Navigation("ServiceType")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
